In [30]:
import numpy as np
import sympy as sy
from numpy import linalg
#define matrix A
A=np.array([[0,1,2],[1,0,3],[4,-3,8]])

#compute eigen values and eigen vectors
eigen_values,eigen_vectors=linalg.eig(A)
print(eigen_vectors)

#extract eigen vectors corresponding to the eigen values
distinct_eigenvalues=[]
distinct_eigenvectors=[]

for i in range(len(eigen_values)):
    if eigen_values[i] not in distinct_eigenvalues:
        distinct_eigenvalues.append(eigen_values[i])
        distinct_eigenvectors.append(eigen_vectors[ : ,i])
        
#create a matrix using distinct eigen vectors
vector_matrix=np.column_stack(distinct_eigenvectors)

#compute rank
rank=linalg.matrix_rank(vector_matrix)
print(rank)

rref_matrix, _ = sy.Matrix(vector_matrix).rref()


[[ 0.26955165  0.90772191 -0.74373492]
 [ 0.36874217  0.24316331 -0.65468206]
 [ 0.88959042 -0.34192476  0.13509171]]
3
Eigenvectors corresponding to distinct eigenvalues are linearly dependent.
